'use client';

import { useMemo, useState } from 'react';
import '../../styles/sections/universal-frame.css';
import '../../styles/sections/da-eater.css';
import { ArtLane, BlueprintStack, ContentScroller, ScenePlate, SectionOverlay, SectionShell } from '../shared/UniversalSectionFrame';
import { buildDaEaterAssurerPayload, calculateDaEaterTotals, deleteCheatFlexEntry, deleteMealEntry, deleteSupplementEntry, formatDisplayDate, getDaEaterDay, saveDaEaterDay, upsertCheatFlexEntry, upsertMealEntry, upsertSupplementEntry } from '../../src/services/daEaterService';

const today = () => new Date().toISOString().slice(0, 10);
const MEAL_TYPES = ['BREAKFAST','LUNCH','DINNER','SNACK','PRE-WORKOUT','POST-WORKOUT','TREAT','DRINK','LATE NIGHT','OTHER'];
const SUP_TYPES = ['VITAMIN','MINERAL','PROTEIN','CREATINE','ELECTROLYTE','DIGESTIVE','PRE-WORKOUT','POST-WORKOUT','OTHER'];
const CHEAT_TYPES = ['CHEAT MEAL','FLEX MEAL','TREAT','REFEED','DATE NIGHT','SOCIAL MEAL','CELEBRATION','OTHER'];

export default function DaEaterSection() {
  const [date, setDate] = useState(today());
  const [day, setDay] = useState(() => getDaEaterDay(today()));
  const [mealForm, setMealForm] = useState({ id: '', type: 'BREAKFAST', name: '', time: '', protein: '', carbs: '', fats: '', calories: '' });
  const [suppForm, setSuppForm] = useState({ id: '', type: 'VITAMIN', name: '', time: '', amount: '', unit: '', notes: '' });
  const [cheatForm, setCheatForm] = useState({ id: '', type: 'CHEAT MEAL', meal: '', dessert: '', roughCalories: '', worthItPercent: '', notes: '' });
  const [cravingNotes, setCravingNotes] = useState({ craving: '', trigger: '', intensity: '', response: '', notes: '' });

  const hydrateDate = (nextDate) => { setDate(nextDate); setDay(getDaEaterDay(nextDate)); setMealForm({ id: '', type: 'BREAKFAST', name: '', time: '', protein: '', carbs: '', fats: '', calories: '' }); };
  const saveDay = (next) => { const saved = saveDaEaterDay(next); setDay(saved); };
  const totals = useMemo(() => calculateDaEaterTotals(day), [day]);
  const assurerPayload = useMemo(() => buildDaEaterAssurerPayload(date, day), [date, day]);
  const dayName = useMemo(() => new Date(`${date}T00:00:00`).toLocaleDateString('en-US', { weekday: 'long' }).toUpperCase(), [date]);

  const saveMeal = () => { const next = upsertMealEntry(date, mealForm); setDay(next); setMealForm({ id: '', type: 'BREAKFAST', name: '', time: '', protein: '', carbs: '', fats: '', calories: '' }); };
  const saveSupplement = () => { const next = upsertSupplementEntry(date, suppForm); setDay(next); setSuppForm({ id: '', type: 'VITAMIN', name: '', time: '', amount: '', unit: '', notes: '' }); };
  const saveCheat = () => { const next = upsertCheatFlexEntry(date, cheatForm); setDay(next); setCheatForm({ id: '', type: 'CHEAT MEAL', meal: '', dessert: '', roughCalories: '', worthItPercent: '', notes: '' }); };

  const shelves = [
    { id: 'A', columns: 1, panels: [{ id: 'macro', token: 'hero-strip', className: 'da-eater-panel', content: <><h2>MACRO DASHBOARD • {formatDisplayDate(date)}</h2><label>DATE<input type="date" value={date} onChange={(e) => hydrateDate(e.target.value)} /></label><label>WATER (OZ)<input value={day.waterOz || ''} onChange={(e) => saveDay({ ...day, waterOz: e.target.value })} /></label>{[['PROTEIN','protein','g'],['CARBS','carbs','g'],['FATS','fats','g'],['CALORIES','calories','cal'],['WATER','waterOz','oz']].map(([label,key,unit]) => { const goal = totals.targets[key]; const current = totals.totals[key]; const p = totals.progress[key]; return <div className="da-eater-macro-row" key={key}><span>{label}</span><span>GOAL {goal}{unit.toUpperCase()}</span><div className="da-eater-bar"><div style={{ width: `${Math.min(p,100)}%` }} /></div><span>{p.toFixed(0)}%</span><span>{Math.max(goal-current,0).toFixed(0)}{unit.toUpperCase()} LEFT</span></div>; })}</> }] },
    { id: 'B', columns: 1, panels: [{ id: 'meals', token: 'medium', className: 'da-eater-panel', content: <><h2>MEAL LOG</h2><div className="da-eater-grid"> <select value={mealForm.type} onChange={(e)=>setMealForm({...mealForm,type:e.target.value})}>{MEAL_TYPES.map((x)=><option key={x}>{x}</option>)}</select><input placeholder="MEAL NAME" value={mealForm.name} onChange={(e)=>setMealForm({...mealForm,name:e.target.value})}/><input type="time" value={mealForm.time} onChange={(e)=>setMealForm({...mealForm,time:e.target.value})}/><input placeholder="PROTEIN" value={mealForm.protein} onChange={(e)=>setMealForm({...mealForm,protein:e.target.value})}/><input placeholder="CARBS" value={mealForm.carbs} onChange={(e)=>setMealForm({...mealForm,carbs:e.target.value})}/><input placeholder="FATS" value={mealForm.fats} onChange={(e)=>setMealForm({...mealForm,fats:e.target.value})}/><input placeholder="CALORIES" value={mealForm.calories} onChange={(e)=>setMealForm({...mealForm,calories:e.target.value})}/></div><button onClick={saveMeal}>SAVE MEAL</button>{(day.meals||[]).map((m)=><div key={m.id} className="da-eater-list-row"><span>{m.type} • {m.name} • {m.time}</span><button onClick={()=>setMealForm(m)}>EDIT</button><button onClick={()=>setDay(deleteMealEntry(date,m.id))}>DELETE</button></div>)}</> }] },
    { id: 'C', columns: 2, panels: [{ id: 'photo', token: 'medium', className: 'da-eater-panel', content: <><h2>PHOTO LOG</h2><div className="da-eater-photo-slot">PHOTO 1 • {formatDisplayDate(date)} • DA.EATER • MEDIA LIBRARY BLOCKED</div><div className="da-eater-photo-slot">PHOTO 2 • {formatDisplayDate(date)} • DA.EATER • MEDIA LIBRARY BLOCKED</div></> }, { id: 'hyper', token: 'medium', className: 'da-eater-panel', content: <><h2>HYPER FIXATION MEAL</h2><input placeholder="MEAL NAME" value={day.hyperFixationMeal?.mealName||''} onChange={(e)=>saveDay({...day,hyperFixationMeal:{...day.hyperFixationMeal,mealName:e.target.value}})} /><input placeholder="CURRENT FIXATION" value={day.hyperFixationMeal?.currentFixation||''} onChange={(e)=>saveDay({...day,hyperFixationMeal:{...day.hyperFixationMeal,currentFixation:e.target.value}})} /><input placeholder="TIMES THIS WEEK" value={day.hyperFixationMeal?.weeklyCount||''} onChange={(e)=>saveDay({...day,hyperFixationMeal:{...day.hyperFixationMeal,weeklyCount:e.target.value}})} /><textarea placeholder="NOTES" value={day.hyperFixationMeal?.notes||''} onChange={(e)=>saveDay({...day,hyperFixationMeal:{...day.hyperFixationMeal,notes:e.target.value}})} /><input placeholder="OPTIONAL MACRO ESTIMATE" value={day.hyperFixationMeal?.macroEstimate||''} onChange={(e)=>saveDay({...day,hyperFixationMeal:{...day.hyperFixationMeal,macroEstimate:e.target.value}})} /></> }] },
    { id: 'D', columns: 2, panels: [{ id: 'supps', token: 'medium', className: 'da-eater-panel', content: <><h2>SUPPLEMENT TRACKING</h2><select value={suppForm.type} onChange={(e)=>setSuppForm({...suppForm,type:e.target.value})}>{SUP_TYPES.map((x)=><option key={x}>{x}</option>)}</select><input placeholder="NAME" value={suppForm.name} onChange={(e)=>setSuppForm({...suppForm,name:e.target.value})}/><input type="time" value={suppForm.time} onChange={(e)=>setSuppForm({...suppForm,time:e.target.value})}/><input placeholder="AMOUNT" value={suppForm.amount} onChange={(e)=>setSuppForm({...suppForm,amount:e.target.value})}/><input placeholder="UNIT" value={suppForm.unit} onChange={(e)=>setSuppForm({...suppForm,unit:e.target.value})}/><textarea placeholder="NOTES" value={suppForm.notes} onChange={(e)=>setSuppForm({...suppForm,notes:e.target.value})}/><button onClick={saveSupplement}>SAVE SUPPLEMENT</button>{(day.supplements||[]).map((s)=><div key={s.id} className="da-eater-list-row"><span>{s.type} • {s.name} • {s.amount}{s.unit}</span><button onClick={()=>setSuppForm(s)}>EDIT</button><button onClick={()=>setDay(deleteSupplementEntry(date,s.id))}>DELETE</button></div>)}</> }, { id: 'craving', token: 'medium', className: 'da-eater-panel da-eater-craving', content: <><h2>CRAVINGS</h2><input placeholder="CRAVING" value={cravingNotes.craving} onChange={(e)=>setCravingNotes({...cravingNotes,craving:e.target.value})}/><input placeholder="TRIGGER" value={cravingNotes.trigger} onChange={(e)=>setCravingNotes({...cravingNotes,trigger:e.target.value})}/><input placeholder="INTENSITY" value={cravingNotes.intensity} onChange={(e)=>setCravingNotes({...cravingNotes,intensity:e.target.value})}/><input placeholder="RESPONSE" value={cravingNotes.response} onChange={(e)=>setCravingNotes({...cravingNotes,response:e.target.value})}/><textarea className="da-eater-lined" placeholder="NOTES" value={cravingNotes.notes} onChange={(e)=>setCravingNotes({...cravingNotes,notes:e.target.value})}/><button onClick={()=>saveDay({...day,cravings:[...(day.cravings||[]),{...cravingNotes,id:Date.now().toString()}]})}>SAVE CRAVING</button></> }] },
    { id: 'E', columns: 1, panels: [{ id: 'cheat', token: 'medium', className: 'da-eater-panel', content: <><h2>CHEAT MEAL WEDNESDAY / SATURDAY {dayName === 'WEDNESDAY' || dayName === 'SATURDAY' ? '(DEFAULT CHEAT DAY)' : ''}</h2><select value={cheatForm.type} onChange={(e)=>setCheatForm({...cheatForm,type:e.target.value})}>{CHEAT_TYPES.map((x)=><option key={x}>{x}</option>)}</select><input placeholder="SLUTTY MEAL" value={cheatForm.meal} onChange={(e)=>setCheatForm({...cheatForm,meal:e.target.value})}/><input placeholder="SLUTTY DESSERT" value={cheatForm.dessert} onChange={(e)=>setCheatForm({...cheatForm,dessert:e.target.value})}/><input placeholder="ROUGH CALORIES" value={cheatForm.roughCalories} onChange={(e)=>setCheatForm({...cheatForm,roughCalories:e.target.value})}/><input placeholder="WORTH IT %" value={cheatForm.worthItPercent} onChange={(e)=>setCheatForm({...cheatForm,worthItPercent:e.target.value})}/><textarea placeholder="NOTES" value={cheatForm.notes} onChange={(e)=>setCheatForm({...cheatForm,notes:e.target.value})}/><button onClick={saveCheat}>SAVE CHEAT/FLEX</button>{(day.cheatFlexEntries||[]).map((c)=><div key={c.id} className="da-eater-list-row"><span>{c.type} • {c.meal}</span><button onClick={()=>setCheatForm(c)}>EDIT</button><button onClick={()=>setDay(deleteCheatFlexEntry(date,c.id))}>DELETE</button></div>)}</> }] },
    { id: 'F', columns: 1, panels: [{ id: 'summary', token: 'standard', className: 'da-eater-panel', content: <><h2>DAILY INTAKE SUMMARY</h2><p>{formatDisplayDate(date)} • {day.meals?.length || 0} MEALS • {day.supplements?.length || 0} SUPPLEMENTS • {day.cravings?.length || 0} CRAVINGS</p><div>PROTEIN {totals.totals.protein} / {totals.targets.protein}G</div><div>CARBS {totals.totals.carbs} / {totals.targets.carbs}G</div><div>FATS {totals.totals.fats} / {totals.targets.fats}G</div><div>CALORIES {totals.totals.calories} / {totals.targets.calories} CAL</div><div>WATER {totals.totals.waterOz} / {totals.targets.waterOz} OZ</div><pre>{JSON.stringify(assurerPayload.signals, null, 2)}</pre></> }] }
  ];

  return <SectionShell className="da-eater-shell"><ScenePlate><div className="da-eater-bg" /></ScenePlate><SectionOverlay><ArtLane className="da-eater-left" /><ContentScroller className="da-eater-content"><BlueprintStack shelves={shelves} /></ContentScroller></SectionOverlay></SectionShell>;
}
