'use client';

import { useEffect, useMemo, useState } from 'react';
import '../../styles/sections/its-getting-thicc.css';
import '../../styles/sections/universal-frame.css';
import { optionRegistry } from '../../lib/dropdowns/optionRegistry';
import {
  appendLog, fetchClientColors, fetchScheduleEntries, loadAssignments, loadClients, loadForms, readMedia, resolveClientColor,
  saveAssignments, saveClients, upsertMedia, upsertScheduleEntry,
} from '../../src/services/itsGettingThiccService';
import { ArtLane, BlueprintStack, ContentScroller, ScenePlate, SectionOverlay, SectionShell } from '../shared/UniversalSectionFrame';

const days = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
const tabs = ['THICC.INFO', 'THICC.PEOPLE', 'THICC.FORMS', 'THICC.TIME'];
const foodPrompts = ['WHAT DO YOU STRUGGLE THE HARDEST TO STAY AWAY FROM', 'WHEN DO YOU USUALLY REACH FOR IT (TIME, MOOD, SITUATION)', 'GROWING UP, WERE YOU FORCED TO FINISH YOUR PLATE, AND HOW HAS THAT AFFECTED YOUR EATING HABITS IN ADULTHOOD?', 'WERE THERE FOOD RULES, PUNISHMENTS, PRESSURE, OR EMOTIONALLY CHARGED EXPERIENCES AROUND EATING GROWING UP THAT STILL AFFECT HOW YOU EAT NOW?', 'HOW DO YOUR EMOTIONS AND FOOD INTERACT TODAY'];
const movementPrompts = ['WALK ME THROUGH A TYPICAL DAY OF EATING', 'WALK ME THROUGH A NORMAL DAY IN YOUR BODY', 'HOW MUCH OF YOUR DAY IS SITTING VS ACTUALLY MOVING', 'WHEN DO YOU FEEL MOST PHYSICALLY ALIVE'];
const medicalPrompts = ['EMERGENCY CONTACT NAME / NUMBER', 'PAST / CURRENT INJURIES', 'PAST / UPCOMING SURGERIES', 'RECURRING SEASONAL ISSUES / ALLERGIES', 'MEDICATIONS THAT COULD CAUSE COMPLICATIONS, LIKE BLOOD PRESSURE MEDS', 'PHYSICAL LIMITATIONS', 'MOVEMENTS THAT CAUSE PAIN', 'LEVEL OF FLEXIBILITY, RANGE FROM RIGAMORTUS TO SIMONE BILES WISHES', 'HARD NO’S', 'TRAINING FEARS'];

export default function ItsGettingThiccSection() {
  const [clients, setClients] = useState([]); const [activeId, setActiveId] = useState(''); const [activeTab, setActiveTab] = useState('THICC.INFO');
  const [forms, setForms] = useState([]); const [assignments, setAssignments] = useState([]); const [calendar, setCalendar] = useState([]); const [colorMap, setColorMap] = useState([]);
  const active = useMemo(() => clients.find((c) => c.id === activeId) || clients[0], [clients, activeId]);

  useEffect(() => { const seeded = loadClients(); setClients(seeded); setForms(loadForms()); setAssignments(loadAssignments()); setActiveId(seeded[0]?.id || ''); fetchScheduleEntries().then(setCalendar); fetchClientColors().then(setColorMap); }, []);
  const persist = (next, event = 'autosave') => { setClients(next); saveClients(next); appendLog(event, { activeId }); };
  const update = (key, value) => { if (!active) return; persist(clients.map((c) => (c.id === active.id ? { ...c, [key]: value } : c)), `field:${key}`); };
  const updateArray = (key, i, value) => update(key, (active[key] || []).map((v, idx) => (idx === i ? value : v)));
  const onUpload = (slot) => (e) => { const f = e.target.files?.[0]; if (!f || !active) return; const fr = new FileReader(); fr.onload = () => { const d = upsertMedia(active.id, slot, fr.result); if (slot === 'photo') update('photo', d); else update('celebration', (active.celebration || []).map((t, i) => (i === Number(slot) ? { ...t, media: d } : t))); }; fr.readAsDataURL(f); };

  if (!active) return null;
  const glancePhoto = active.photo || readMedia(active.id, 'photo');

  function Food() { return <><h3>FOOD: THE GOOD, THE BAD & THE “I DESERVE THIS”</h3>{foodPrompts.map((p, i) => <label key={p}>{`${i + 1}. ${p}`}<textarea value={active[`food${i + 1}`] || ''} onChange={(e) => update(`food${i + 1}`, e.target.value)} /></label>)}</>; }
  function Movement() { return <><h3>MOVEMENT: THE MEASURE AND THE PRESSURES</h3>{movementPrompts.map((p, i) => <label key={p}>{`${i + 1}. ${p}`}{i === 1 && <small>THINK WORK, ERRANDS, SITTING, STANDING, STEPS, STRESS, AND HOW OFTEN YOUR BODY IS ACTUALLY IN MOTION, NOT JUST HOW OFTEN YOU MEANT TO WORK OUT.</small>}<textarea value={active[`move${i + 1}`] || ''} onChange={(e) => update(`move${i + 1}`, e.target.value)} /></label>)}<label>5. SELECT CURRENT OVERALL LEVEL OF ACTIVITY<select value={active.activity || 'SEDENTARY'} onChange={(e) => update('activity', e.target.value)}>{['SEDENTARY', 'LIGHTLY', 'MODERATELY', 'ACTIVE', 'I DO THIS S@$&!', 'I SWEAR I’M ACTIVE BUT MY APPLE WATCH SAYS OTHERWISE'].map((o) => <option key={o}>{o}</option>)}</select></label></>; }
  function Medical() { const keys=['emergencyContact','injuries','surgeries','allergies','medications','limits','painfulMovements','flexibility','hardNos','trainingFears']; return <><h3>MEDICAL ADVISORY</h3>{medicalPrompts.map((p, i) => <label key={p}>{`${i + 1}. ${p}`}<textarea value={active[keys[i]] || ''} onChange={(e) => update(keys[i], e.target.value)} /></label>)}</>; }

  const infoShelves = [
    { id: 'A', columns: 1, panels: [{ id: 'core', token: 'tall', className:'igtv2-client-core', content: <><h3>THICC.STATS</h3><div className="client-core-grid"><div>{['name','id','phone','sex','sexualOrientation','height','age','email','relationshipStatus','clientColorOptionKey','currentWeight','goalWeight','currentBmi','goalBmi'].map((k) => <label key={k}>{k==='relationshipStatus'?'MARRIED / SINGLE':k==='phone'?'PHONE NUMBER':k==='sexualOrientation'?'SEXUAL ORIENTATION':k==='clientColorOptionKey'?'CLIENT COLOR':k.replace(/([A-Z])/g,' $1').toUpperCase()}{k==='clientColorOptionKey'?<select value={active.clientColorOptionKey||''} onChange={(e)=>update('clientColorOptionKey',e.target.value)}>{optionRegistry.itsGettingThicc.clientColors.map((o)=><option key={o.key} value={o.key}>{o.label}</option>)}</select>:k==='relationshipStatus'?<select value={active.relationshipStatus||'SINGLE'} onChange={(e)=>update('relationshipStatus',e.target.value)}><option>SINGLE</option><option>MARRIED</option></select>:<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} />}</label>)}</div><div className="portrait-bay"><label className="upload">{glancePhoto ? <img src={glancePhoto} alt="client" /> : 'PHOTO UPLOAD FROM LIBRARY'}<input type="file" accept="image/*" onChange={onUpload('photo')} /></label></div></div></> }] },
    { id: 'B', columns: 1, panels: [{ id: 'food', token: 'tall', content: <Food /> }] },
    { id: 'C', columns: 2, panels: [{ id: 'move', token: 'tall', content: <Movement /> }, { id: 'med', token: 'tall', content: <Medical /> }] },
    { id: 'D', columns: 4, panels: [
      { id: 'macro', token: 'standard', content: <><h3>MACRO TARGETS</h3><div className="macro-inline-wrap">{[['macro_protein','PROTEIN'],['macro_carbs','CARBS'],['macro_fats','FATS'],['macro_water','WATER'],['macro_calories','CALORIES']].map(([k,l])=><label key={k}>{l}<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} /></label>)}</div></> },
      { id: 'vault', token: 'standard', content: <><h3>VAULT</h3>{[['juice_substance','COMPOUND'],['juice_ester','ESTER / FORM'],['juice_amount','AMOUNT'],['juice_shot','SHOT __ OF __'],['juice_sensitivity','SENSITIVITY / SIDE EFFECTS'],['juice_cycle','CYCLE WEEK __ OF __'],['juice_location','LOCATION'],['juice_notes','NOTES']].map(([k,l])=><label key={k}>{l}{k.includes('notes')||k.includes('sensitivity')?<textarea value={active[k]||''} onChange={(e)=>update(k,e.target.value)} />:<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} />}</label>)}</> },
      { id: 'spw', token: 'standard', content: <><h3>SEASONS PER WEEK</h3><input value={active.seasonsPerWeek||''} onChange={(e)=>update('seasonsPerWeek',e.target.value)} /></> },
      { id: 'ref', token: 'standard', content: <><h3>REFERRAL TRACKER</h3>{(active.referrals||[]).slice(0,1).map((r,i)=><div key={i} className="form-row"><input placeholder="NAME" value={r.name||''} onChange={(e)=>update('referrals',[{...r,name:e.target.value}])}/><input placeholder="DATE" value={r.date||''} onChange={(e)=>update('referrals',[{...r,date:e.target.value}])}/><input placeholder="STATUS" value={r.status||''} onChange={(e)=>update('referrals',[{...r,status:e.target.value}])}/></div>)}<textarea placeholder="NOTES" value={active.referrals?.[0]?.notes||''} onChange={(e)=>update('referrals',[{...(active.referrals?.[0]||{}),notes:e.target.value}])} /></> },
    ]},
    { id: 'E', columns: 1, panels: [{ id: 'train', token: 'tall', className:'igtv2-training-system', content: <><h3>TRAINING SYSTEM</h3><div className="training-system-band"><h4>TRAINING / REST</h4><div className="hz">{days.map((d,i)=><label key={d}>{d}<select value={active.trainingRest?.[i]||'TRAINING'} onChange={(e)=>updateArray('trainingRest',i,e.target.value)}>{optionRegistry.itsGettingThicc.trainingRest.map((o)=><option key={o}>{o}</option>)}</select></label>)}</div></div><div className="training-system-band"><h4>CURRENT EXERCISE PROGRAM SPLIT / WORKOUT DAY</h4><div className="hz">{days.map((d,i)=><label key={d}>{d}<select value={active.programSplit?.[i]||'FULLBODY'} onChange={(e)=>updateArray('programSplit',i,e.target.value)}>{optionRegistry.itsGettingThicc.programSplit.map((o)=><option key={o}>{o}</option>)}</select></label>)}</div></div></> }] },
    { id: 'F', columns: 2, panels: [{ id: 'event', token: 'standard', content: <><h3>UPCOMING TRAINING FOCUS EVENTS</h3><textarea value={active.eventNotes||''} onChange={(e)=>update('eventNotes',e.target.value)} /></> }, { id: 'pay', token: 'standard', content: <><h3>PAYMENT</h3><input value={active.paymentDate||''} onChange={(e)=>update('paymentDate',e.target.value)} /></> }] },
    { id: 'G', columns: 2, panels: [{ id: 'thoughts', token: 'tall', content: <><h3>THICC THOUGHTS</h3><textarea className="notes" value={active.thoughts||''} onChange={(e)=>update('thoughts',e.target.value)} /></> }, { id: 'myfit', token: 'standard', content: <><h3>MYFITFOODS CHECK-IN</h3><label>WEEKLY # OF MEALS ______<input value={active.myfitMeals||''} onChange={(e)=>update('myfitMeals',e.target.value)} /></label><label>HAS BEEN VERIFIED BY ANTHONY Y / N<select value={active.myfitVerified ? 'Y' : 'N'} onChange={(e)=>update('myfitVerified', e.target.value === 'Y')}><option>Y</option><option>N</option></select></label></> }] },
    { id: 'H', columns: 1, panels: [{ id: 'cele', token: 'tall', content: <><h3>CELEBRATION MOMENTS</h3><div className="cele">{(active.celebration || []).slice(0, 10).map((tile, i) => <div key={tile.id || i} className="slot"><textarea placeholder="CELEBRATION MOMENT" value={tile.text || ''} onChange={(e) => update('celebration', (active.celebration || []).map((t, idx) => (idx === i ? { ...t, text: e.target.value } : t)))} />{tile.media ? <img src={tile.media} alt="" /> : null}<input type="file" accept="image/*" onChange={onUpload(String(i))} /><button className="inline-del" onClick={() => update('celebration', (active.celebration || []).map((t, idx) => (idx === i ? { ...t, text: '', media: '' } : t)))}>×</button></div>)}</div></> }] },
  ];

  const peopleShelves = [{ id: 'people', columns: 1, panels: [{ id: 'p1', token: 'medium', content: <><h3>THICC.PEOPLE</h3><div className="people-list">{clients.map((c) => { const cc = resolveClientColor(c.clientColorOptionKey); return <button key={c.id} className="people-item" style={{ borderLeftColor: cc.value }} onClick={() => { setActiveId(c.id); setActiveTab('THICC.INFO'); }}><div><strong>{c.name}</strong><span>{c.id}</span></div><div><em style={{ color: cc.value }}>{cc.label}</em><span>{c.active === false ? 'INACTIVE' : 'ACTIVE'}</span></div></button>; })}</div></> }] }];
  const formsShelves = [{ id: 'forms', columns: 1, panels: [{ id: 'f1', token: 'medium', content: <><h3>THICC.FORMS</h3>{forms.map((f) => <div key={f.id} className="form-row"><strong>{f.formName}</strong><span>{f.formCategory}</span><button onClick={() => { const next = [...assignments, { id: Date.now(), clientId: active.id, formId: f.id, status: 'assigned', response_json: {}, notes: '' }]; setAssignments(next); saveAssignments(next); }}>ASSIGN</button></div>)}<p>ASSIGNMENTS {assignments.filter((a) => a.clientId === active.id).length}</p></> }] }];
  const timeShelves = [{ id: 'time', columns: 1, panels: [{ id: 't1', token: 'ultra', content: <><h3>THICC.TIME</h3><div className="month">{Array.from({ length: 35 }).map((_, i) => <div key={i} className="day"><b>{i + 1 <= 31 ? i + 1 : ''}</b>{calendar.filter((r) => Number(r.entry_date?.slice(-2)) === i + 1).map((r) => <div key={r.id} className="booking" style={{ background: r.entry_type === 'personal' ? '#ff4db8' : (colorMap.find((c) => c.key === r.color_option_key)?.value || resolveClientColor(r.color_option_key).value) }}>{r.workout_label || 'BOOKING'}</div>)}</div>)}</div><button onClick={async () => { const created = await upsertScheduleEntry({ id: String(Date.now()), client_id: active.id, entry_type: 'client', entry_date: new Date().toISOString().slice(0, 10), workout_label: active.programSplit?.[new Date().getDay()] || 'SESSION', source_split_day: days[new Date().getDay()], color_option_key: active.clientColorOptionKey || 'cobalt' }); setCalendar((prev) => [...prev, created]); }}>ADD ENTRY</button></> }] }];

  const shelves = activeTab === 'THICC.INFO' ? infoShelves : activeTab === 'THICC.PEOPLE' ? peopleShelves : activeTab === 'THICC.FORMS' ? formsShelves : timeShelves;
  return <SectionShell className="igtv2-page"><ScenePlate className="igtv2-scene-plate"><div className="igtv2-bg" /></ScenePlate><SectionOverlay><ArtLane className="igtv2-left"><div className="igtv2-glyph">ITS</div><div className="igtv2-cabinet">{tabs.map((tab) => <button key={tab} className={`igtv2-cabinet-btn ${activeTab === tab ? 'active' : ''}`} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div></ArtLane><ContentScroller><BlueprintStack shelves={shelves.map((s) => s.id === 'time' ? ({ ...s, panels: s.panels.map((p) => ({ ...p, className: 'igtv2-time-panel' })) }) : s)} /></ContentScroller></SectionOverlay></SectionShell>;
}
