'use client';

import { useEffect, useMemo, useState } from 'react';
import '../../styles/sections/its-getting-thicc.css';
import '../../styles/sections/universal-frame.css';
import { optionRegistry } from '../../lib/dropdowns/optionRegistry';
import { addClient, appendLog, loadClients, readMedia, saveClients, upsertMedia } from '../../src/services/itsGettingThiccService';
import { ArtLane, BlueprintStack, ContentScroller, ScenePlate, SectionOverlay, SectionShell } from '../shared/UniversalSectionFrame';

const days = ['SUN','MON','TUE','WED','THU','FRI','SAT']; const cabinetTabs = ['THICC.INFO','THICC.PEOPLE','THICC.FORMS','THICC.TIME'];
const tokenByArea={2:'medium',3:'standard',4:'standard',5:'tall',6:'tall',7:'standard',8:'compact',9:'compact',10:'strip',11:'standard',12:'standard',13:'compact',14:'compact',15:'medium',16:'compact',17:'medium',18:'standard',19:'strip'};
export default function ItsGettingThiccSection(){const [clients,setClients]=useState([]);const [activeId,setActiveId]=useState('');const [activeTab,setActiveTab]=useState('THICC.INFO');const active=useMemo(()=>clients.find((c)=>c.id===activeId)||clients[0],[clients,activeId]);
useEffect(()=>{const seeded=loadClients();setClients(seeded);setActiveId(seeded[0]?.id||'');},[]);const persist=(next,event='autosave')=>{setClients(next);saveClients(next);appendLog(event,{activeId});};
const update=(key,value)=>{if(!active)return;const next=clients.map((c)=>(c.id===active.id?{...c,[key]:value}:c));if(key==='name'){const clean=value.trim().toLowerCase().replace(/\s+/g,'-');persist(next.map((c)=>(c.id===active.id?{...c,fileName:clean||c.id.toLowerCase()}:c)),`field:${key}:rename`);return;}persist(next,`field:${key}`);};
const updateArray=(key,i,value)=>update(key,(active[key]||[]).map((v,idx)=>(idx===i?value:v))); const onUpload=(slot)=>(e)=>{const f=e.target.files?.[0];if(!f||!active)return;const fr=new FileReader();fr.onload=()=>{const dataUrl=upsertMedia(active.id,slot,fr.result);if(slot==='photo')update('photo',dataUrl);else updateArray('celebration',Number(slot),dataUrl);};fr.readAsDataURL(f);}; if(!active)return null; const glancePhoto=active.photo||readMedia(active.id,'photo');
const area={
2:<>{activeTab==='THICC.INFO'&&<><h3>2. BODY / GOAL</h3>{['currentWeight','goalWeight','currentBmi','goalBmi'].map((k)=><label key={k}>{k.replace(/([A-Z])/g,' $1').toUpperCase()}<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} /></label>)}</>}</>,
3:<>{activeTab==='THICC.INFO'&&<><h3>3. AT A GLANCE</h3>{glancePhoto&&<img src={glancePhoto} alt="glance" className="thumb" />}<p>HEIGHT: {active.heightFt}' {active.heightIn}"</p><p>CURRENT WEIGHT: {active.currentWeight}</p><p>GOAL WEIGHT: {active.goalWeight}</p></>}</>,
4:<>{activeTab==='THICC.INFO'&&<><h3>4. FOOD</h3>{[1,2,3,4,5].map((n)=><label key={n}>Q{n}<textarea value={active[`food${n}`]||''} onChange={(e)=>update(`food${n}`,e.target.value)} /></label>)}</>}</>,
5:<>{activeTab==='THICC.INFO'&&<><h3>5. MOVEMENT</h3>{[1,2,3,4].map((n)=><label key={n}>Q{n}<textarea value={active[`move${n}`]||''} onChange={(e)=>update(`move${n}`,e.target.value)} /></label>)}<label>ACTIVITY LEVEL<select value={active.activity||''} onChange={(e)=>update('activity',e.target.value)}><option value="" />{optionRegistry.itsGettingThicc.activityLevel.map((o)=><option key={o}>{o}</option>)}</select></label></>}</>,
6:<>{activeTab==='THICC.INFO'&&<><h3>6. MEDICAL ADVISORY</h3>{[['medEmergency','EMERGENCY'],['medInjuries','INJURIES'],['medSurgeries','SURGERIES'],['medAllergies','ALLERGIES'],['medMeds','MEDICATIONS'],['medLimits','LIMITS'],['medPain','PAIN'],['medFlex','FLEXIBILITY'],['medHardNo','HARD NO'],['medFears','FEARS']].map(([k,l])=><label key={k}>{l}<textarea value={active[k]||''} onChange={(e)=>update(k,e.target.value)} /></label>)}</>}</>,
7:<>{activeTab==='THICC.INFO'&&<><h3>7. MACRO TARGETS</h3>{['macroProtein','macroCarbs','macroFats','macroWater','macroCalories'].map((k)=><label key={k}>{k}<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} /></label>)}</>}</>,
8:<>{activeTab==='THICC.INFO'&&<><h3>8. DA.JUICE MIRROR</h3>{[['juiceSubstance','SUBSTANCE'],['juiceShot','AMOUNT'],['juiceCycle','CYCLE'],['juiceLocation','LOCATION'],['juiceNotes','NOTES']].map(([k,l])=><label key={k}>{l}<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} /></label>)}</>}</>,
9:<>{activeTab==='THICC.INFO'&&<><h3>9. SEASONS PER WEEK</h3><label>SEASONS<input type="number" value={active.seasonsPerWeek||''} onChange={(e)=>update('seasonsPerWeek',e.target.value)} /></label></>}</>,
10:<>{activeTab==='THICC.INFO'&&<><h3>10. REFERRAL TRACKER</h3><button onClick={()=>update('referrals',[...active.referrals,{name:'',date:'',status:''}])}>ADD REFERRAL</button></>}</>,
11:<>{activeTab==='THICC.INFO'&&<><h3>11. TRAINING / REST</h3><div className="hz">{days.map((d,i)=><label key={d}>{d}<select value={active.trainingRest?.[i]||'TRAINING'} onChange={(e)=>updateArray('trainingRest',i,e.target.value)}>{optionRegistry.itsGettingThicc.trainingRest.map((o)=><option key={o}>{o}</option>)}</select></label>)}</div></>}</>,
12:<>{activeTab==='THICC.INFO'&&<><h3>12. PROGRAM SPLIT</h3><div className="hz">{days.map((d,i)=><label key={d}>{d}<select value={active.programSplit?.[i]||'FULLBODY'} onChange={(e)=>updateArray('programSplit',i,e.target.value)}>{optionRegistry.itsGettingThicc.programSplit.map((o)=><option key={o}>{o}</option>)}</select></label>)}</div></>}</>,
13:<>{activeTab==='THICC.INFO'&&<><h3>13. EVENTS</h3><textarea value={active.upcomingEventsNotes||''} onChange={(e)=>update('upcomingEventsNotes',e.target.value)} /></>}</>,
14:<>{activeTab==='THICC.INFO'&&<><h3>14. PAYMENT</h3><label>DATE<input type="date" value={active.paymentDate||''} onChange={(e)=>update('paymentDate',e.target.value)} /></label></>}</>,
15:<>{activeTab==='THICC.INFO'&&<><h3>15. THOUGHTS</h3><textarea className="big" value={active.thoughts||''} onChange={(e)=>update('thoughts',e.target.value)} /></>}</>,
16:<>{activeTab==='THICC.INFO'&&<><h3>16. MYFITFOODS CHECK-IN</h3><textarea value={active.myfitNotes||''} onChange={(e)=>update('myfitNotes',e.target.value)} /></>}</>,
17:<>{activeTab==='THICC.INFO'&&<><h3>17. CELEBRATION MOMENTS</h3><div className="cele">{(active.celebration||[]).map((img,i)=><label key={i} className="slot">{img?<img src={img} alt=""/>:`${i+1}`}<input type="file" accept="image/*" onChange={onUpload(String(i))}/></label>)}</div></>}</>,
18:<>{activeTab==='THICC.INFO'&&<><h3>1. CLIENT IDENTITY</h3><label>PHOTO</label><label className="upload">{glancePhoto?<img src={glancePhoto} alt="client"/>:'UPLOAD'}<input type="file" accept="image/*" onChange={onUpload('photo')} /></label>{['name','id','phone','age','email'].map((k)=><label key={k}>{k.toUpperCase()}<input value={active[k]||''} onChange={(e)=>update(k,e.target.value)} /></label>)}</>}</>,
19:<>{activeTab==='THICC.INFO'&&<button className="inline-del" onClick={()=>{const next=clients.filter((c)=>c.id!==active.id);persist(next,'delete-client');setActiveId(next[0]?.id||'');}}>DELETE CLIENT</button>}</>
};
const shelves=[['A',[2]],['B',[3,4]],['C',[5]],['D',[6,7]],['E',[8,9,10,11]],['F',[12,13]],['G',[14,15]],['H',[16,17]],['I',[18]]].map(([id,ids])=>({id,columns:ids.length,panels:ids.map((pid)=>({id:`${pid}`,token:tokenByArea[pid],content:area[pid]}))})); shelves[shelves.length-1].panels[0].content=<>{area[18]}{area[19]}</>;
if(activeTab==='THICC.PEOPLE') shelves.splice(1,shelves.length-1,{id:'people',columns:1,panels:[{id:'people',token:'medium',content:<><h3>SAVED CLIENT PROFILES</h3><div className="people-list">{clients.map((client)=><button key={client.id} className={`people-item ${active.id===client.id?'active':''}`} onClick={()=>{setActiveId(client.id);setActiveTab('THICC.INFO');}}><span>{client.name||client.id}</span><span>{client.id}</span></button>)}</div></>}]});
return <SectionShell className="igtv2-page"><ScenePlate><div className="igtv2-bg" /><div className="igtv2-shade" /></ScenePlate><SectionOverlay><ArtLane className="igtv2-left"><div className="igtv2-cabinet">{cabinetTabs.map((tab)=><button key={tab} className={`igtv2-cabinet-btn ${activeTab===tab?'active':''}`} onClick={()=>setActiveTab(tab)}>{tab}</button>)}</div></ArtLane><ContentScroller><BlueprintStack shelves={shelves} /></ContentScroller></SectionOverlay></SectionShell>;
}
