'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import '../../styles/sections/thicc-fitt.css';
import { optionRegistry } from '../../lib/dropdowns/optionRegistry';

const STORAGE_KEY = 'thicc_fitt_day';
const EXERCISE_COUNT = 6;
const initialExercise = { exercise: '', weight: '', reps: '', sets: '', failure: 'N', notes: '' };
const bodyRows = [['weight', 'WEIGHT (LBS)'], ['bodyFat', 'BODY FAT (%)'], ['chest', 'CHEST (IN)'], ['waist', 'WAIST (IN)'], ['arms', 'ARMS L / R (IN)'], ['thighs', 'THIGHS L / R (IN)'], ['glutes', 'GLUTES (IN)']];

const initialState = { control: { gymLocation: 'CHAOTICA', arrivalTime: '', workoutLength: '', seasonPhase: '', sorenessRecovery: '', prepStatus: '' }, exerciseRows: Array.from({ length: EXERCISE_COUNT }, () => ({ ...initialExercise })), coreFocus: '', coreMinutes: '15:00', trainingDuration: '', sessionTotal: '', sessionCompleted: '', cardio: { type: '', duration: '', intensity: '', location: '', notes: '', weeklyDone: 0 }, vault: { compound: '', ester: '', amount: '', shotCurrent: '', shotTotal: '', sensitivity: '', cycleWeekCurrent: '', cycleWeekTotal: '' }, body: Object.fromEntries(bodyRows.map(([k]) => [k, { today: '', lastWeek: '', change: '' }])), quoteOfDay: optionRegistry.thiccFitt.quoteOfDay[0], soHowYouDoin: optionRegistry.thiccFitt.soHowYouDoin[0], soHowYouDoinNotes: '', photo: { nextShoot: '', targetMonth: '', daysRemaining: '', submissionStatus: 'NOT SUBMITTED', lastSubmitted: '', history: '' }, inbody: { lastScan: '', notes: '', history: '' } };

export default function ThiccFittSection() {
  const [state, setState] = useState(initialState);
  useEffect(() => { const raw = localStorage.getItem(STORAGE_KEY); if (raw) setState((p) => ({ ...p, ...JSON.parse(raw) })); }, []);
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state]);
  const update = (section, key, value) => setState((p) => ({ ...p, [section]: { ...p[section], [key]: value } }));
  const updateExercise = (i, key, value) => setState((p) => ({ ...p, exerciseRows: p.exerciseRows.map((r, n) => (i === n ? { ...r, [key]: value } : r)) }));
  const cardioComplianceLabel = useMemo(() => `${state.cardio.weeklyDone} / 3`, [state.cardio.weeklyDone]);

  return <section className="tf30-shell"><div className="tf30-bg" /><div className="tf30-overlay" />
    <section className="tf30-content-shell">
      <Link href="/clock-it" className="tf30-clock">CLOCK.IT</Link>
      <aside className="tf30-left"><Link href="/its-getting-thicc" className="tf30-crystal"><img src="/ui/glyphs/triggers/glyph-crystal-dumbbell.png" alt="DUMBBELL" /><span>CLIENT SYSTEM ACCESS</span></Link></aside>

      <section className="tf30-right"><header className="tf30-island tf30-band"><label>GYM<input value={state.control.gymLocation} onChange={(e) => update('control', 'gymLocation', e.target.value)} /></label><label>ARRIVAL<input type="time" value={state.control.arrivalTime} onChange={(e) => update('control', 'arrivalTime', e.target.value)} /></label><label>WORKOUT LENGTH<select value={state.control.workoutLength} onChange={(e) => update('control', 'workoutLength', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidWorkoutDuration.map((o) => <option key={o}>{o}</option>)}</select></label><label>SEASON / PHASE<select value={state.control.seasonPhase} onChange={(e) => update('control', 'seasonPhase', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidSeason.map((o) => <option key={o}>{o}</option>)}</select></label><label>SORENESS / RECOVERY<input value={state.control.sorenessRecovery} onChange={(e) => update('control', 'sorenessRecovery', e.target.value)} /></label><label>PREP STATUS<input value={state.control.prepStatus} onChange={(e) => update('control', 'prepStatus', e.target.value)} /></label></header>
        <main className="tf30-grid">
          <section className="tf30-island tf30-exercise"><h2>EXERCISE LOG 2.0</h2><div className="tf30-table-head"><span>#</span><span>EXERCISE</span><span>WEIGHT</span><span>REPS</span><span>SETS</span><span>FAILURE</span><span>NOTES</span></div>{state.exerciseRows.map((r, i) => <div className="tf30-table-row" key={i}><span>{i + 1}</span><input value={r.exercise} onChange={(e) => updateExercise(i, 'exercise', e.target.value)} /><input value={r.weight} onChange={(e) => updateExercise(i, 'weight', e.target.value)} /><input value={r.reps} onChange={(e) => updateExercise(i, 'reps', e.target.value)} /><input value={r.sets} onChange={(e) => updateExercise(i, 'sets', e.target.value)} /><select value={r.failure} onChange={(e) => updateExercise(i, 'failure', e.target.value)}><option>Y</option><option>N</option></select><input value={r.notes} onChange={(e) => updateExercise(i, 'notes', e.target.value)} /></div>)}<div className="tf30-core"><label>CORE WORK (15 MINUTES)<input value={state.coreFocus} onChange={(e) => setState((p) => ({ ...p, coreFocus: e.target.value }))} /></label><label>CORE TIME<input value={state.coreMinutes} onChange={(e) => setState((p) => ({ ...p, coreMinutes: e.target.value }))} /></label><div /></div><div className="tf30-duration"><label>TRAINING DURATION<input value={state.trainingDuration} onChange={(e) => setState((p) => ({ ...p, trainingDuration: e.target.value }))} /></label><label>SESSION TOTAL<input value={state.sessionTotal} onChange={(e) => setState((p) => ({ ...p, sessionTotal: e.target.value }))} /></label><label>COMPLETED<input value={state.sessionCompleted} onChange={(e) => setState((p) => ({ ...p, sessionCompleted: e.target.value }))} /></label></div></section>
          <section className="tf30-island tf30-vault"><h2>THE VAULT 2.0</h2><div className="tf30-vault-glyph">◉</div><label>COMPOUND<select value={state.vault.compound} onChange={(e) => update('vault', 'compound', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidCompound.map((o) => <option key={o}>{o}</option>)}</select></label><label>ESTER / FORM<select value={state.vault.ester} onChange={(e) => update('vault', 'ester', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidEster.map((o) => <option key={o}>{o}</option>)}</select></label><label>AMOUNT<select value={state.vault.amount} onChange={(e) => update('vault', 'amount', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidAmount.map((o) => <option key={o}>{o}</option>)}</select></label><label>SHOT __ OF __<div><input value={state.vault.shotCurrent} onChange={(e) => update('vault', 'shotCurrent', e.target.value)} /><input value={state.vault.shotTotal} onChange={(e) => update('vault', 'shotTotal', e.target.value)} /></div></label><label>SENSITIVITY<select value={state.vault.sensitivity} onChange={(e) => update('vault', 'sensitivity', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidSensitivity.map((o) => <option key={o}>{o}</option>)}</select></label><label>CYCLE WEEK __ OF __<div><input value={state.vault.cycleWeekCurrent} onChange={(e) => update('vault', 'cycleWeekCurrent', e.target.value)} /><input value={state.vault.cycleWeekTotal} onChange={(e) => update('vault', 'cycleWeekTotal', e.target.value)} /></div></label></section>
          <section className="tf30-island tf30-cardio"><h2>CARDIO / CONDITIONING</h2><div className="tf30-split"><div><label>CARDIO TYPE<select value={state.cardio.type} onChange={(e) => update('cardio', 'type', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidCardioType.map((o) => <option key={o}>{o}</option>)}</select></label><label>CARDIO DURATION<select value={state.cardio.duration} onChange={(e) => update('cardio', 'duration', e.target.value)}><option value="">--</option>{optionRegistry.thiccFitt.roidCardioDuration.map((o) => <option key={o}>{o}</option>)}</select></label><label>CARDIO INTENSITY<input value={state.cardio.intensity} onChange={(e) => update('cardio', 'intensity', e.target.value)} /></label><label>LOCATION<input value={state.cardio.location} onChange={(e) => update('cardio', 'location', e.target.value)} /></label><label>NOTES<textarea value={state.cardio.notes} onChange={(e) => update('cardio', 'notes', e.target.value)} /></label></div><div><strong>WEEKLY CARDIO GOAL</strong><div>3X PER WEEK</div><label>WEEKLY PROGRESS<input type="number" min="0" max="3" value={state.cardio.weeklyDone} onChange={(e) => update('cardio', 'weeklyDone', Number(e.target.value) || 0)} /></label><strong>{cardioComplianceLabel}</strong></div></div></section>
          <section className="tf30-island tf30-quote"><h2>THICC.QUOTE OF THE DAY</h2><select value={state.quoteOfDay} onChange={(e) => setState((p) => ({ ...p, quoteOfDay: e.target.value }))}>{optionRegistry.thiccFitt.quoteOfDay.map((o) => <option key={o}>{o}</option>)}</select><blockquote>{state.quoteOfDay}</blockquote></section>
          <section className="tf30-island tf30-doin"><h2>SO HOW YOU DOIN 🫪⁉️</h2><select value={state.soHowYouDoin} onChange={(e) => setState((p) => ({ ...p, soHowYouDoin: e.target.value }))}>{optionRegistry.thiccFitt.soHowYouDoin.map((o) => <option key={o}>{o}</option>)}</select><textarea value={state.soHowYouDoinNotes} onChange={(e) => setState((p) => ({ ...p, soHowYouDoinNotes: e.target.value }))} /></section>
          <section className="tf30-island tf30-photo"><h2>PHOTO SHOOT COUNTDOWN</h2><label>NEXT SHOOT<input value={state.photo.nextShoot} onChange={(e) => update('photo', 'nextShoot', e.target.value)} /></label><label>TARGET MONTH (LAST SATURDAY)<input value={state.photo.targetMonth} onChange={(e) => update('photo', 'targetMonth', e.target.value)} /></label><label>DAYS REMAINING<input value={state.photo.daysRemaining} onChange={(e) => update('photo', 'daysRemaining', e.target.value)} /></label><label>SUBMISSION STATUS<input value={state.photo.submissionStatus} onChange={(e) => update('photo', 'submissionStatus', e.target.value)} /></label><label>LAST SUBMITTED<input value={state.photo.lastSubmitted} onChange={(e) => update('photo', 'lastSubmitted', e.target.value)} /></label><label>CHECKPOINT HISTORY<input value={state.photo.history} onChange={(e) => update('photo', 'history', e.target.value)} /></label></section>
          <section className="tf30-island tf30-body"><h2>BODY / GROWTH TRACKING</h2><div className="tf30-metric-head"><span>METRIC</span><span>TODAY</span><span>LAST WEEK</span><span>CHANGE</span></div>{bodyRows.map(([k, l]) => <div className="tf30-metric-row" key={k}><span>{l}</span><input value={state.body[k].today} onChange={(e) => setState((p) => ({ ...p, body: { ...p.body, [k]: { ...p.body[k], today: e.target.value } } }))} /><input value={state.body[k].lastWeek} onChange={(e) => setState((p) => ({ ...p, body: { ...p.body, [k]: { ...p.body[k], lastWeek: e.target.value } } }))} /><input value={state.body[k].change} onChange={(e) => setState((p) => ({ ...p, body: { ...p.body, [k]: { ...p.body[k], change: e.target.value } } }))} /></div>)}</section>
          <section className="tf30-island tf30-inbody"><h2>INBODY SCAN (WEEKLY - SATURDAY)</h2><label>LAST SCAN<input value={state.inbody.lastScan} onChange={(e) => update('inbody', 'lastScan', e.target.value)} /></label><label>SPIKES / NOTES<input value={state.inbody.notes} onChange={(e) => update('inbody', 'notes', e.target.value)} /></label><label>HISTORY ACCESS<input value={state.inbody.history} onChange={(e) => update('inbody', 'history', e.target.value)} /></label></section>
          <section className="tf30-island tf30-media"><h2>MEDIA</h2><div className="tf30-media-grid"><div>PROGRESS PHOTOS</div><div>GYM PHOTOS</div><div>CHECKPOINT PHOTOS</div></div></section>
        </main><footer className="tf30-island tf30-footer"><span>MIN 75 MIN</span><span>MAX 120 MIN</span><span>CORE 15 MIN</span><span>CARDIO 60 MIN / 3X WEEK</span><span>INBODY WEEKLY SATURDAY</span><span>PROGRESS REMINDER</span></footer></section>
    </section>
  </section>;
}
