export const optionRegistry = {
  thiccFitt: {
    soHowYouDoin: [
      'I WON’T SUM MO COACH GIMME THAT','THAT WAS DEFINITELY NOT A FART','OK TEAM LET’S CALL IT… TIME OF DEATH IS 🫪','SHE ATE BUT SHE IS SEEING STARS','I NEED A STRETCH, A SNACK, AND A MAN','I FEAR I HAVE LEFT MY SOUL ON THE LEG PRESS','GAGGED, SWEATY, AND STILL EMPLOYED','I LOOK INSANE BUT THE PUMP IS CORRECT','SOMEBODY HOLD MY PURSE AND MY VISION','I COULD CRY BUT MY GLUTES WON’T LET ME','THIS WAS HOTTER THAN IT WAS HEALTHY','I AM BOTH GOD’S STRONGEST AND WEAKEST SOLDIER','BABY I AM COOKED BUT NOT DONE','MY BODY SAID NO BUT MY EGO SAID AGAIN','IF I SIT DOWN IT IS OVER','I NEED WATER, CARBS, AND QUIET','THAT CARDIO WAS AN ACT OF VIOLENCE','I SURVIVED BUT LET’S NOT ROMANTICIZE IT','PUMPED, FILTHY, AND SPIRITUALLY REARRANGED','PUT ME IN THE VAULT AND SEAL THE DOOR'
    ],
    roidSeason: ['BULKING', 'CUTTING', 'RECOMP', 'MAINTENANCE'],
    roidWorkoutDuration: ['30 MIN', '45 MIN', '60 MIN', '90 MIN'],
    roidCardioType: ['RUN', 'BIKE', 'STAIRMASTER', 'WALK'],
    roidCardioDuration: ['10 MIN', '20 MIN', '30 MIN', '45 MIN'],
    roidCompound: ['TESTOSTERONE', 'NANDROLONE', 'TRENBOLONE', 'ANAVAR'],
    roidEster: ['CYPIONATE', 'ENANTHATE', 'ACETATE', 'UNDECANOATE'],
    roidAmount: ['100 MG', '200 MG', '300 MG', '500 MG'],
    roidSensitivity: ['LOW', 'MEDIUM', 'HIGH'],
    quoteOfDay: [
      { id: 'thicc-quote-001', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 001: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-002', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 002: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-003', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 003: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-004', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 004: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-005', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 005: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-006', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 006: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-007', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 007: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-008', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 008: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-009', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 009: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-010', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 010: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-011', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 011: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-012', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 012: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-013', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 013: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-014', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 014: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-015', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 015: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-016', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 016: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-017', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 017: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-018', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 018: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-019', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 019: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-020', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 020: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-021', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 021: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-022', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 022: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-023', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 023: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-024', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 024: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-025', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 025: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-026', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 026: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-027', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 027: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-028', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 028: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-029', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 029: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-030', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 030: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-031', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 031: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-032', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 032: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-033', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 033: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-034', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 034: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-035', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 035: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-036', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 036: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-037', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 037: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-038', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 038: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-039', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 039: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-040', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 040: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-041', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 041: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-042', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 042: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-043', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 043: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-044', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 044: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-045', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 045: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-046', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 046: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-047', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 047: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-048', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 048: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-049', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 049: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-050', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 050: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-051', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 051: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-052', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 052: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-053', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 053: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-054', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 054: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-055', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 055: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-056', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 056: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-057', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 057: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-058', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 058: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-059', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 059: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' },
      { id: 'thicc-quote-060', family: 'thiccQuoteDaily', intensity: 'HIGH', text: 'QUOTE 060: DISCIPLINE CLOCKED. FORM VERIFIED. RESULTS EARNED.' }
    ]

  },
  assessment: {
    mood: ['FOCUSED', 'OPTIMISTIC', 'CAUTIOUS', 'OVERWHELMED'],
    era: ['RESET', 'REBUILD', 'ASCENT', 'MAINTENANCE'],
    singlenessLevel: ['SINGLE', 'COMPLICATED', 'PARTNERED'],
    libidoCheckIn: ['LOW', 'STEADY', 'HIGH']
  },
  rememberMeFuture: {
    psTypes: ['P.S. TYPE A', 'P.S. TYPE B'],
    momentTypes: ['MOMENT TYPE A', 'MOMENT TYPE B']
  },
  itsGettingThicc: {
    sex: ['MALE', 'FEMALE', 'OTHER'],
    sexualOrientation: ['STRAIGHT', 'GAY', 'BI', 'OTHER'],
    activityLevel: ['SEDENTARY', 'LIGHTLY', 'MODERATELY', 'ACTIVE', 'I DO THIS S@$&!', "I SWEAR I\'M ACTIVE BUT MY APPLE WATCH SAYS OTHERWISE"],
    referralStatus: ['NONE', 'REFERRED', 'BONUS APPLIED'],
    trainingRest: ['TRAINING', 'REST'],
    programSplit: ['FULLBODY', 'UPPER', 'LOWER'],
    upcomingTrainingEventType: ['WEDDING', 'ANNIVERSARY', 'BIRTHDAY', 'VACATION', 'UPCOMING SURGERY', 'CUSTOM'],
    paymentSchedule: ['WEEKLY', 'BI-WEEKLY', 'MONTHLY'],
    flexibilityLevel: ['LOW', 'MODERATE', 'HIGH'],
    marriedSingle: ['MARRIED', 'SINGLE'],
    clientColors: [
      { key:'cobalt', label:'COBALT', value:'#3b82f6', active:true, display_order:1 },
      { key:'emerald', label:'EMERALD', value:'#10b981', active:true, display_order:2 },
      { key:'amber', label:'AMBER', value:'#f59e0b', active:true, display_order:3 },
      { key:'violet', label:'VIOLET', value:'#8b5cf6', active:true, display_order:4 },
      { key:'teal', label:'TEAL', value:'#14b8a6', active:true, display_order:5 },
      { key:'indigo', label:'INDIGO', value:'#6366f1', active:true, display_order:6 },
      { key:'slate', label:'SLATE', value:'#64748b', active:true, display_order:7 },
      { key:'orange', label:'ORANGE', value:'#f97316', active:true, display_order:8 },
      { key:'cyan', label:'CYAN', value:'#06b6d4', active:true, display_order:9 },
      { key:'lime', label:'LIME', value:'#84cc16', active:true, display_order:10 },
      { key:'sky', label:'SKY', value:'#0ea5e9', active:true, display_order:11 },
      { key:'navy', label:'NAVY', value:'#1e3a8a', active:true, display_order:12 },
      { key:'plum', label:'PLUM', value:'#7e22ce', active:true, display_order:13 },
      { key:'gold', label:'GOLD', value:'#ca8a04', active:true, display_order:14 },
      { key:'olive', label:'OLIVE', value:'#65a30d', active:true, display_order:15 },
      { key:'mint', label:'MINT', value:'#34d399', active:true, display_order:16 },
      { key:'aqua', label:'AQUA', value:'#22d3ee', active:true, display_order:17 },
      { key:'steel', label:'STEEL', value:'#475569', active:true, display_order:18 },
      { key:'chocolate', label:'CHOCOLATE', value:'#92400e', active:true, display_order:19 },
      { key:'sand', label:'SAND', value:'#d97706', active:true, display_order:20 },
      { key:'forest', label:'FOREST', value:'#166534', active:true, display_order:21 },
      { key:'sea', label:'SEA', value:'#0f766e', active:true, display_order:22 },
      { key:'ice', label:'ICE', value:'#0891b2', active:true, display_order:23 },
      { key:'storm', label:'STORM', value:'#334155', active:true, display_order:24 },
      { key:'royal', label:'ROYAL', value:'#4338ca', active:true, display_order:25 },
      { key:'orchid', label:'ORCHID', value:'#9333ea', active:true, display_order:26 },
      { key:'ruby2', label:'RUBY', value:'#b91c1c', active:true, display_order:27 },
      { key:'brick', label:'BRICK', value:'#c2410c', active:true, display_order:28 },
      { key:'sage', label:'SAGE', value:'#4d7c0f', active:true, display_order:29 },
      { key:'ocean', label:'OCEAN', value:'#0369a1', active:true, display_order:30 }
    ],

  }
};
