export const optionRegistry = {
  thiccFitt: {
    soHowYouDoin: [
      'I WON’T SUM MO COACH GIMME THAT','THAT WAS DEFINITELY NOT A FART','OK TEAM LET’S CALL IT… TIME OF DEATH IS 🫪','SHE ATE BUT SHE IS SEEING STARS','I NEED A STRETCH, A SNACK, AND A MAN','I FEAR I HAVE LEFT MY SOUL ON THE LEG PRESS','GAGGED, SWEATY, AND STILL EMPLOYED','I LOOK INSANE BUT THE PUMP IS CORRECT','SOMEBODY HOLD MY PURSE AND MY VISION','I COULD CRY BUT MY GLUTES WON’T LET ME','THIS WAS HOTTER THAN IT WAS HEALTHY','I AM BOTH GOD’S STRONGEST AND WEAKEST SOLDIER','BABY I AM COOKED BUT NOT DONE','MY BODY SAID NO BUT MY EGO SAID AGAIN','IF I SIT DOWN IT IS OVER','I NEED WATER, CARBS, AND QUIET','THAT CARDIO WAS AN ACT OF VIOLENCE','I SURVIVED BUT LET’S NOT ROMANTICIZE IT','PUMPED, FILTHY, AND SPIRITUALLY REARRANGED','PUT ME IN THE VAULT AND SEAL THE DOOR'
    ],
    roidSeason: ['BULKING', 'CUTTING', 'RECOMP', 'MAINTENANCE'],
    roidWorkoutDuration: ['30 MIN', '45 MIN', '60 MIN', '90 MIN'],
    roidCardioType: ['RUN', 'BIKE', 'STAIRMASTER', 'WALK'],
    roidCardioDuration: ['10 MIN', '20 MIN', '30 MIN', '45 MIN'],
    roidCompound: ['TESTOSTERONE', 'NANDROLONE', 'TRENBOLONE', 'ANAVAR'],
    roidEster: ['CYPIONATE', 'ENANTHATE', 'ACETATE', 'UNDECANOATE'],
    roidAmount: ['100 MG', '200 MG', '300 MG', '500 MG'],
    roidSensitivity: ['LOW', 'MEDIUM', 'HIGH'],
    quoteOfDay: [
      'SWEAT NOW, STUNT LATER.',
      'THE PUMP IS THE PROOF.',
      'BUILT LOUD. RECOVER LOUDER.',
      'HEAVY WORK. CLEAN FORM. NO APOLOGIES.',
      'DISCIPLINE IN GLITTER MODE.',
      'YOU DID NOT COME THIS FAR TO COAST.'
    ]
  },
  assessment: {
    mood: ['FOCUSED', 'OPTIMISTIC', 'CAUTIOUS', 'OVERWHELMED'],
    era: ['RESET', 'REBUILD', 'ASCENT', 'MAINTENANCE'],
    singlenessLevel: ['SINGLE', 'COMPLICATED', 'PARTNERED'],
    libidoCheckIn: ['LOW', 'STEADY', 'HIGH']
  },
  rememberMeFuture: {
    psTypes: ['P.S. TYPE A', 'P.S. TYPE B'],
    momentTypes: ['MOMENT TYPE A', 'MOMENT TYPE B']
  },
  itsGettingThicc: {
    sex: ['MALE', 'FEMALE', 'OTHER'],
    sexualOrientation: ['STRAIGHT', 'GAY', 'BI', 'OTHER'],
    activityLevel: ['SEDENTARY', 'LIGHTLY', 'MODERATELY', 'ACTIVE', 'I DO THIS S@$&!', "I SWEAR I\'M ACTIVE BUT MY APPLE WATCH SAYS OTHERWISE"],
    referralStatus: ['NONE', 'REFERRED', 'BONUS APPLIED'],
    trainingRest: ['TRAINING', 'REST'],
    programSplit: ['FULLBODY', 'UPPER', 'LOWER'],
    upcomingTrainingEventType: ['WEDDING', 'ANNIVERSARY', 'BIRTHDAY', 'VACATION', 'UPCOMING SURGERY', 'CUSTOM'],
    paymentSchedule: ['WEEKLY', 'BI-WEEKLY', 'MONTHLY'],
    flexibilityLevel: ['LOW', 'MODERATE', 'HIGH'],
    marriedSingle: ['MARRIED', 'SINGLE']
  }
};
